[project]
name = "image-template"
version = "0.2.0"
description = "Copier template to easily set up docker projects on Github"
authors = [{ name = "Tecnativa" }]
requires-python = ">=3.9,<4"
dependencies = [
]

[dependency-groups]
dev = [
    "copier>=9.10.3",
    "jsonschema>=4.25.1",
    "pre-commit-uv>=4.1.5",
    "pre-commit>=4.3.0",
    "pytest-xdist>=3.8.0",
    "pytest>=8.4.2",
    "python-on-whales>=0.81.0",
]

[tool.uv]
package = false

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "I",   # isort
    "UP",  # pyupgrade
]

[tool.pytest.ini_options]
addopts = "-n auto -ra"
